#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-deploy
  labels:
    app: pet-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pet-app
  template:
    metadata:
      labels:
        app: pet-app
    spec:
      containers:
      - name: petclinicweb
        image: cicdcontainer/webappproject:1.0
        ports:
        - containerPort: 8888
