apiVersion: v1
kind: Service
metadata:
  name: pet-service
  labels:
    app: pet-app
    
spec:
  selector:
    app: pet-app
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080

