

name: deployent

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: deploy war totomcat
      run:   curl -v -u admin:admin -T /home/runner/work/petproject/petproject/target/spring-petclinic-4.2.war 'http://13.235.19.131:8080/manager/text/deploy?path=/spring-petclinic-4.2.war'


    
   
